### ISSUE TITLE
Use ngx-uploader in a service

### ISSUE THREAD

**Issue by MrCroft** [jkuri/ngx-uploader#252]
Hi,

Is there an example of using ngx-uploader in a service?
How we would associate it with a ngFileDrop/ngFileSelect, but still have access to progress/complete response after navigating away from the current route? (navigating away - means that the component which contains ngFileDrop/ngFileSelect would get destroyed).

Scenario: on drag&drop files, autoupload starts. Then, the user should be able to freely navigate in your app, while having some floating info displaying the progress of all his/her uploads that haven't yet finished uploading.
Problem is that, as soon as the route changes, even though the upload is still being done in the background, I loose all data regarding it (progress, response on complete). Therefore, this should be done in a service... But I have no idea how.

Also, creating multiple instances programmatically would be required, because the user might want to upload another batch of uploads while the previous one hasn't finished yet, and there might be separate data to be edited/entered for each batch. Anyway, this probably has less to do with ngx-uploader itself, but more with app logic (just wanted to mention this in case there is something that would prevent having multiple instances to work correctly). 

I blindly tried to adapt the demo example in a service, instead of a component, and thought to directly make use of NgUploaderService, but I quickly stopped because I really have no clue how to use ngx-uploader, other than the strict two simple examples [here](http://ngx-uploader.com/demo) and [here](http://ngx-uploader.com/advanced).

Any other advanced examples out there, that involve using a service?

**Comment by jkuri** [comment]
hi @MrCroft. good point, actually I am just working on a complete rewrite of the whole module which will be done in the next days coming. I'll try to cover all the usage examples on the demo page. I'll keep you posted. thanks!

**Comment by lgleim** [comment]
any updates on when this will be available?

**Comment by jkuri** [comment]
hi @lgleim I just pushed to https://github.com/jkuri/ngx-uploader/tree/3.0.0 new branch. I am pretty much done with uploading features but there's still work to be done (documentation ofc). 
I will do my best to finish this till the Sunday evening or Monday morning.

**Comment by jkuri** [comment]
hey guys new version published as `3.0.0`. For more info see README and check online demo on http://ngx-uploader.com. Thanks!

**Comment by MrCroft** [comment]
Newb here... Works great at component level. Unfortunately, I still don't know how to properly make it work in a service.
I've put all the code from the demo in a service (`UploadService`).
Then, in my component (which is loaded in the dashboard home) I tried the following (to simply use the service):
```
    public uploadInput;

    constructor(private uploadService: UploadService) {
        this.uploadInput = this.uploadService.uploadInput;
    }


    onUploadOutput(output: UploadOutput): void {
        this.uploadService.onUploadOutput(output);
    }

    /**
     * No need to use this, because the upload is set to auto in the service.
     */
    startUpload(): void {  // manually start uploading
        const event: UploadInput = {
            type: 'uploadAll',
            url: 'http://localhost:3000/upload',
            method: 'POST',
            data: { hash: this.uploadService.generateHash() },
            concurrency: 0 // set sequential uploading of files with concurrency 1
        }

        this.uploadService.uploadInput.emit(event);
    }

    cancelUpload(id: string): void {
        this.uploadService.uploadInput.emit({ type: 'cancel', id: id });
    }
```
I've stripped the app of everything else, leaving just the upload part plus some basic routing. I've created a repo here: https://github.com/MrCroft/ngx-uploader-demo (all the below is also included in the readme).

Any pointers towards the right direction? Has anybody succeeded in doing something like this?

**Issues:**
1. Even though the uploader code is in a service, it is still coupled with the file input in my component and it stops logging to the console as soon as we navigate away from the dashboard/home component. I don't know how to decouple that.
2. Multiple uploads should send all the files in a single request (unrelated to the initial question).

**Step 1:** Either upload a very large file or enable some throttling in the chrome developer tools to emulate a very slow connection.
**Step 2:** Click to select files **or** drag and drop files. The upload starts.
**Step 3:** Watch the console. It keeps logging "uploading" (good). I look in the network tab, the request says "pending". So far so good.
**Step 4:** Navigate to any other route in the app. The console.log() immediately stops.
The request in the network tab still says pending (and the upload is still happening, it will be finished at some point - unless I stop the server or close the browser tab entirely).
Also, if I navigate to the dashboard/home component, after having navigated away previously, I get an error: `Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed`

### Desired scenario:
1. When I navigate to any other route in my app (after having started an upload), I still need the upload service to keep logging to the console ().
Plan is to store all uploads which are in progress in an array in the service and have an event emitter to which I can subscribe and listen to in any other component in my app, so I can show the user any the data regarding the uploads in progress, anywhere else I might choose to in the app (like in `http://localhost:4200/queue` for example, or `http://localhost/queue/some-hash`).

2. Every file select (or drag and drop) operation, multiple or not, should launch one request instead of `number of requests = number of files dropped`.
Right now, if I multiple-select 10 files, I see 10 requests (well, actually it's 20 in my case, because of the preflight, since the server is on another domain).
The hash I create and add to the data that's being sent to the server (`data: { hash: this.generateHash() }`) seems to be per operation, not per file - which is good, because it helps to keep track of the files as a group, server-side. 
But the fact that it doesn't send multiple files in one request, makes it extremely difficult to have an overall progress (per upload batch).

**Comment by MrCroft** [comment]
@jkuri any news on an example?

**Comment by jkuri** [comment]
@MrCroft give me some minutes, I'll check now.

**Comment by jkuri** [comment]
hey man, can you ping me tomorrow please, I will solve this for you but haven't sleep for two days. been checking now but haven't found a solution already, I am kinda dizzy. okay?

**Comment by MrCroft** [comment]
Sure thing! Thank you so much for looking into it.
I'm sure that what I've tried doesn't make much sense also...

Will ping you tomorrow. Thanks again!
And have a good night!

**Comment by MrCroft** [comment]
ping! :)

**Comment by jkuri** [comment]
hi :) thanks. I'll let you know when ready.

**Comment by jkuri** [comment]
hey @MrCroft, I am attaching source files here. I needed to create custom directive to make your case work. hope this will gets you going, if you need further help, let me know. 

[MrCroft-client.zip](https://github.com/jkuri/ngx-uploader/files/972022/MrCroft-client.zip)

**Comment by MrCroft** [comment]
Awesome! Thank you very much!
I'll check it out right away!

I owe you! If I can ever help you out with anything, let me know!

**Comment by MrCroft** [comment]
Works great! I think I shouldn't have any problems with creating a custom `fileDrop` directive also, that will look mainly like the `fileSelect` one, only different event listeners.

**Comment by GustavoCostaW** [comment]
Hey @jkuri @MrCroft I have the same problem, I need to continue my upload when the user changes the active router from the component that has directive uploader. Checking the code source, I can make this not using the directive because when It's destroyed unsubscribe is called. I created the singleton service and using the 'API' directly checking the source. @MrCroft, congratz for code, but, I believe the service is the better way to use your lib and these directives is a one way to use. I think the nice way is focused your lib in a service, because all application can upload files in the same instance and the progress continue even the user change the router and get the active upload progress any time with the service, using this with directives and call unsubscribe this not possible, isn't possible get active upload files in another component, you need to save the var 'files' in another service to get the values, and other problems... If you want help for the service to provide the way to use your lib I can help you for make this possible. Thank you! (sorry for English :p)

**Comment by MrCroft** [comment]
Hi @GustavoCostaW 
Yes, right now, for every upload I save all the data in my service and check that from any component where I might need that data.
The directive is needed, though... customized a bit. But, once an upload is added, the service takes over and continues to work as the user navigates.
Did you check the code in the archive attached above by @jkuri ? Because I haven't updated my repo... so, if that's the code you checked, that doesn't work.

**Comment by GustavoCostaW** [comment]
@MrCroft yep, but he needed to create a custom directive to do this, and the main idea of this lib works with directives and limits the service and, unfortunately, has some limitations.

I'm working in a complex panel to upload most files asynchronous and the user can navigate in all application and the upload progress continue in 'background mode' ( like Google Drive. ) and react events, for make this possible, I'm changing very things in lib and add new features, like 

- Singleton service
- Using Angular Injector Dependency (why you need create NgUploadService manually?)
- passing custom properties in uploadFile type, (It's created in handleFiles)
- new events like allFilesHaveBeenUploaded
- not dependencies with directives, you can use the service normally and with simple way.

Well, there are still some features to be added, I do not know if the creator ( @jkuri ) of the lib will accept a pull request, so I'll probably make a fork of the project.

**Comment by HarelM** [comment]
Same here, I have a `fileService` that is responsible to handle everything that is related to files. I want to use this library with it, but it can't be done without an upload service...

**Comment by lgleim** [comment]
A singleton service-based approach definitely does look like the most reasonable approach for this library.

@GustavoCostaW Have your released your code yet?
@jkuri Would you be willing to accept a pull request with corresponding changes?

**Comment by HarelM** [comment]
I was hoping to use this library to replace the following code in one of my services:
```
public upload(url: string, file: File): Promise<Response> {
        return new Promise((resolve, reject) => {

            let xhr: XMLHttpRequest = new XMLHttpRequest();
            xhr.onreadystatechange = () => {
                if (xhr.readyState === 4) {
                    if (xhr.status === 200) {
                        resolve(xhr.response);
                    } else {
                        reject(xhr.response);
                    }
                }
            };

            xhr.open('POST', Urls.openFile, true);
            
            let formData = new FormData();
            formData.append("file", file, file.name);
            xhr.send(formData);
        });
    }
```
Unfortunately the service in this library does not accept `File` objects. The main reason was that I wanted to be able to test my service and it wasn't straight forward in term of mocking xhr and all its operations.
Any thoughts are welcome, I would be delighted to remove all reference of xhr from my code as it doesn't feel "Angularish"...

**Comment by vecernik** [comment]
Angular 4.4: ObjectUnsubscribedError error when ngFileSelect or ngFileDrop (!) is used in one of router states.

**Comment by xts-velkumars** [comment]
@MrCroft 

have you achieved using fileService. If yes can you please share your code.
